name: Build Tugas 6

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile C++
        shell: bash
        run: g++ tugas_6.cpp -o tugas_6.exe -static

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: tugas_6-ex
          path: tugas_6.exe
